namespace RandaSports.Persistence.Seeders;

/// <param name="Aliases">Haber metninde geçebilecek diğer yazımlar. Kısa ve yanıltıcı olanları koyma ("FB", "GS").</param>
public sealed record TeamSeed(string Name, string Country, bool IsNational, string[] Aliases);

/// <summary>
/// Takım sözlüğü. Kümeleme buradan besleniyor: listede olmayan isim takım sayılmaz,
/// böylece sponsor, mekan ve marka adları haberleri kirletmez.
/// </summary>
public static class TeamSeedData
{
    public static readonly TeamSeed[] FootballClubs =
    [
        new("Galatasaray", "Türkiye", false, ["G.Saray", "Cimbom", "Galatasaray SK"]),
        new("Fenerbahçe", "Türkiye", false, ["F.Bahçe", "Fener", "Fenerbahçe SK"]),
        new("Beşiktaş", "Türkiye", false, ["Beşiktaş JK", "Kartal"]),
        new("Trabzonspor", "Türkiye", false, ["Trabzon", "Fırtına"]),
        new("Başakşehir", "Türkiye", false, ["RAMS Başakşehir", "İstanbul Başakşehir"]),
        new("Samsunspor", "Türkiye", false, ["Yılport Samsunspor"]),
        new("Kasımpaşa", "Türkiye", false, ["Kasımpaşa SK"]),
        new("Konyaspor", "Türkiye", false, ["Tümosan Konyaspor"]),
        new("Antalyaspor", "Türkiye", false, ["Bitexen Antalyaspor"]),
        new("Alanyaspor", "Türkiye", false, ["Corendon Alanyaspor"]),
        new("Kayserispor", "Türkiye", false, ["Mondihome Kayserispor"]),
        new("Sivasspor", "Türkiye", false, ["Demir Grup Sivasspor"]),
        new("Gaziantep FK", "Türkiye", false, ["Gaziantep Futbol Kulübü"]),
        new("Çaykur Rizespor", "Türkiye", false, ["Rizespor"]),
        new("Göztepe", "Türkiye", false, ["Göztepe SK"]),
        new("Eyüpspor", "Türkiye", false, ["İstanbul Eyüpspor"]),
        new("Kocaelispor", "Türkiye", false, []),
        new("Gençlerbirliği", "Türkiye", false, []),
        new("Karagümrük", "Türkiye", false, ["Fatih Karagümrük"]),
        new("Hatayspor", "Türkiye", false, []),
        new("Bodrum FK", "Türkiye", false, ["Bodrumspor"]),
        new("Adana Demirspor", "Türkiye", false, ["Demirspor"]),
        new("MKE Ankaragücü", "Türkiye", false, ["Ankaragücü"]),
        new("Pendikspor", "Türkiye", false, []),
        new("İstanbulspor", "Türkiye", false, []),
        new("Ümraniyespor", "Türkiye", false, []),
        new("Giresunspor", "Türkiye", false, []),
        new("Bandırmaspor", "Türkiye", false, []),
        new("Erzurumspor FK", "Türkiye", false, ["Erzurumspor"]),
        new("Boluspor", "Türkiye", false, []),
        new("Sakaryaspor", "Türkiye", false, []),
        new("Manisa FK", "Türkiye", false, []),
        new("Şanlıurfaspor", "Türkiye", false, ["Urfaspor"]),
        new("Çorum FK", "Türkiye", false, []),
        new("Keçiörengücü", "Türkiye", false, ["Ankara Keçiörengücü"]),
        new("Vanspor FK", "Türkiye", false, ["Vanspor"]),
        new("Amed Sportif", "Türkiye", false, ["Amedspor"]),
        new("Bursaspor", "Türkiye", false, []),
        new("Denizlispor", "Türkiye", false, []),
        new("Altay", "Türkiye", false, ["Altay SK"]),
        new("Iğdır FK", "Türkiye", false, ["Iğdırspor"]),
        new("Esenler Erokspor", "Türkiye", false, ["Erokspor"]),
        new("Serik Spor", "Türkiye", false, ["Serikspor"]),
        new("Menemen FK", "Türkiye", false, ["Menemenspor"]),
        new("Real Madrid", "İspanya", false, ["Madrid"]),
        new("Barcelona", "İspanya", false, ["Barça", "FC Barcelona"]),
        new("Atletico Madrid", "İspanya", false, ["Atletico"]),
        new("Sevilla", "İspanya", false, []),
        new("Villarreal", "İspanya", false, []),
        new("Athletic Bilbao", "İspanya", false, ["Bilbao"]),
        new("Manchester United", "İngiltere", false, ["Man United", "Manchester Utd"]),
        new("Manchester City", "İngiltere", false, ["Man City"]),
        new("Liverpool", "İngiltere", false, []),
        new("Chelsea", "İngiltere", false, []),
        new("Arsenal", "İngiltere", false, []),
        new("Tottenham", "İngiltere", false, ["Tottenham Hotspur"]),
        new("Newcastle United", "İngiltere", false, ["Newcastle"]),
        new("Aston Villa", "İngiltere", false, []),
        new("West Ham", "İngiltere", false, ["West Ham United"]),
        new("Bayern Münih", "Almanya", false, ["Bayern Munich", "Bayern"]),
        new("Borussia Dortmund", "Almanya", false, ["Dortmund"]),
        new("RB Leipzig", "Almanya", false, ["Leipzig"]),
        new("Bayer Leverkusen", "Almanya", false, ["Leverkusen"]),
        new("Eintracht Frankfurt", "Almanya", false, ["Frankfurt"]),
        new("Juventus", "İtalya", false, ["Juve"]),
        new("Inter", "İtalya", false, ["Inter Milan", "Internazionale"]),
        new("Milan", "İtalya", false, ["AC Milan"]),
        new("Napoli", "İtalya", false, []),
        new("Roma", "İtalya", false, ["AS Roma"]),
        new("Lazio", "İtalya", false, []),
        new("Atalanta", "İtalya", false, []),
        new("Fiorentina", "İtalya", false, []),
        new("Frosinone", "İtalya", false, []),
        new("Paris Saint-Germain", "Fransa", false, ["PSG", "Paris SG"]),
        new("Marsilya", "Fransa", false, ["Olympique Marsilya", "Marseille"]),
        new("Lyon", "Fransa", false, ["Olympique Lyon"]),
        new("Monaco", "Fransa", false, ["AS Monaco"]),
        new("Lille", "Fransa", false, []),
        new("Ajax", "Hollanda", false, []),
        new("PSV Eindhoven", "Hollanda", false, ["PSV"]),
        new("Feyenoord", "Hollanda", false, []),
        new("Benfica", "Portekiz", false, []),
        new("Porto", "Portekiz", false, ["FC Porto"]),
        new("Sporting Lizbon", "Portekiz", false, ["Sporting"]),
        new("Celtic", "İskoçya", false, []),
        new("Rangers", "İskoçya", false, []),
        new("Olympiakos", "Yunanistan", false, []),
        new("Panathinaikos", "Yunanistan", false, []),
        new("Shakhtar Donetsk", "Ukrayna", false, ["Shakhtar"]),
        new("Zenit", "Rusya", false, ["Zenit St. Petersburg"]),
        new("Santos", "Brezilya", false, ["Santos FC"]),
        new("Flamengo", "Brezilya", false, []),
        new("Palmeiras", "Brezilya", false, []),
        new("Boca Juniors", "Arjantin", false, ["Boca"]),
        new("River Plate", "Arjantin", false, [])
    ];

    public static readonly TeamSeed[] NationalTeams =
    [
        new("Türkiye", "Türkiye", true, ["A Millî Takım", "Türkiye Millî Takımı", "Millî Takım"]),
        new("İtalya", "İtalya", true, ["İtalya Millî Takımı"]),
        new("İspanya", "İspanya", true, []),
        new("Almanya", "Almanya", true, []),
        new("Fransa", "Fransa", true, []),
        new("İngiltere", "İngiltere", true, []),
        new("Portekiz", "Portekiz", true, []),
        new("Hollanda", "Hollanda", true, []),
        new("Belçika", "Belçika", true, []),
        new("Hırvatistan", "Hırvatistan", true, []),
        new("Sırbistan", "Sırbistan", true, []),
        new("Avusturya", "Avusturya", true, []),
        new("İsviçre", "İsviçre", true, []),
        new("Danimarka", "Danimarka", true, []),
        new("İsveç", "İsveç", true, []),
        new("Norveç", "Norveç", true, []),
        new("Polonya", "Polonya", true, []),
        new("Çekya", "Çekya", true, ["Çek Cumhuriyeti"]),
        new("Slovakya", "Slovakya", true, []),
        new("Slovenya", "Slovenya", true, []),
        new("Macaristan", "Macaristan", true, []),
        new("Romanya", "Romanya", true, []),
        new("Bulgaristan", "Bulgaristan", true, []),
        new("Ukrayna", "Ukrayna", true, []),
        new("Gürcistan", "Gürcistan", true, []),
        new("Yunanistan", "Yunanistan", true, []),
        new("Galler", "Galler", true, []),
        new("İskoçya", "İskoçya", true, []),
        new("İrlanda", "İrlanda", true, []),
        new("İzlanda", "İzlanda", true, []),
        new("Finlandiya", "Finlandiya", true, []),
        new("Bosna Hersek", "Bosna Hersek", true, []),
        new("Karadağ", "Karadağ", true, []),
        new("Arnavutluk", "Arnavutluk", true, []),
        new("Kuzey Makedonya", "Kuzey Makedonya", true, []),
        new("Azerbaycan", "Azerbaycan", true, []),
        new("Kazakistan", "Kazakistan", true, []),
        new("Brezilya", "Brezilya", true, []),
        new("Arjantin", "Arjantin", true, []),
        new("Uruguay", "Uruguay", true, []),
        new("Kolombiya", "Kolombiya", true, []),
        new("Şili", "Şili", true, []),
        new("Peru", "Peru", true, []),
        new("Paraguay", "Paraguay", true, []),
        new("Ekvador", "Ekvador", true, []),
        new("Meksika", "Meksika", true, []),
        new("Amerika Birleşik Devletleri", "ABD", true, ["ABD"]),
        new("Kanada", "Kanada", true, []),
        new("Japonya", "Japonya", true, []),
        new("Güney Kore", "Güney Kore", true, ["Kore Cumhuriyeti"]),
        new("Avustralya", "Avustralya", true, []),
        new("İran", "İran", true, []),
        new("Suudi Arabistan", "Suudi Arabistan", true, []),
        new("Katar", "Katar", true, []),
        new("Fas", "Fas", true, []),
        new("Senegal", "Senegal", true, []),
        new("Mısır", "Mısır", true, []),
        new("Nijerya", "Nijerya", true, []),
        new("Gana", "Gana", true, []),
        new("Cezayir", "Cezayir", true, []),
        new("Tunus", "Tunus", true, []),
        new("Kamerun", "Kamerun", true, []),
        new("Fildişi Sahili", "Fildişi Sahili", true, []),
        new("Güney Afrika", "Güney Afrika", true, []),
        new("Yeşil Burun Adaları", "Yeşil Burun Adaları", true, ["Cape Verde"]),
        new("Filistin", "Filistin", true, [])
    ];

    public static readonly TeamSeed[] BasketballClubs =
    [
        new("Anadolu Efes", "Türkiye", false, ["Efes"]),
        new("Fenerbahçe Beko", "Türkiye", false, []),
        new("Galatasaray Ekmas", "Türkiye", false, []),
        new("Türk Telekom", "Türkiye", false, []),
        new("Pınar Karşıyaka", "Türkiye", false, ["Karşıyaka"]),
        new("Tofaş", "Türkiye", false, ["Tofaş SK"]),
        new("Bahçeşehir Koleji", "Türkiye", false, []),
        new("Merkezefendi Belediyesi", "Türkiye", false, ["Merkezefendi"]),
        new("Beşiktaş Fibabanka", "Türkiye", false, []),
        new("Büyükçekmece Basketbol", "Türkiye", false, ["Büyükçekmece"]),
        new("Darüşşafaka", "Türkiye", false, []),
        new("Aliağa Petkimspor", "Türkiye", false, ["Petkimspor"]),
        new("Biotekno Körfez Basket", "Türkiye", false, ["Körfez Basket"])
    ];
}
