// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RandaSports.Persistence.Contexts;

#nullable disable

namespace RandaSports.Persistence.Migrations
{
    [DbContext(typeof(RandaSportsDbContext))]
    [Migration("20261005134736_AddCommentatorIsVerified")]
    partial class AddCommentatorIsVerified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChannelCommentator", b =>
                {
                    b.Property<Guid>("ChannelsId")
                        .HasColumnType("uuid")
                        .HasColumnName("channels_id");

                    b.Property<Guid>("RegularCommentatorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("regular_commentators_id");

                    b.HasKey("ChannelsId", "RegularCommentatorsId")
                        .HasName("pk_channel_commentators");

                    b.HasIndex("RegularCommentatorsId")
                        .HasDatabaseName("ix_channel_commentators_regular_commentators_id");

                    b.ToTable("channel_commentators", (string)null);
                });

            modelBuilder.Entity("CommentatorSport", b =>
                {
                    b.Property<Guid>("CommentatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("commentator_id");

                    b.Property<Guid>("SportsId")
                        .HasColumnType("uuid")
                        .HasColumnName("sports_id");

                    b.HasKey("CommentatorId", "SportsId")
                        .HasName("pk_commentator_sports");

                    b.HasIndex("SportsId")
                        .HasDatabaseName("ix_commentator_sports_sports_id");

                    b.ToTable("commentator_sports", (string)null);
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsId")
                        .HasColumnType("uuid")
                        .HasColumnName("competitions_id");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid")
                        .HasColumnName("teams_id");

                    b.HasKey("CompetitionsId", "TeamsId")
                        .HasName("pk_competition_teams");

                    b.HasIndex("TeamsId")
                        .HasDatabaseName("ix_competition_teams_teams_id");

                    b.ToTable("competition_teams", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("ai_analysis");

                    b.Property<int>("AiAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("ai_attempts");

                    b.Property<string>("AiBody")
                        .HasColumnType("text")
                        .HasColumnName("ai_body");

                    b.Property<string>("AiDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_data_json");

                    b.Property<string>("AiHeadline")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ai_headline");

                    b.Property<bool>("AiIsLive")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_is_live");

                    b.Property<DateTimeOffset?>("AiProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_processed_at");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<string>("Author")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("excerpt");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid?>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("AiProcessedAt")
                        .HasDatabaseName("ix_articles_ai_processed_at")
                        .HasFilter("ai_processed_at IS NULL");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_articles_published_at");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_articles_source_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_articles_story_id")
                        .HasFilter("story_id IS NULL");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_url");

                    b.HasIndex("SportId", "PublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_articles_sport_id_published_at");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.ArticleTag", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.HasKey("ArticleId", "EntityType", "EntityId")
                        .HasName("pk_article_tags");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_article_tags_entity_type_entity_id");

                    b.ToTable("article_tags", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Appearances")
                        .HasColumnType("integer")
                        .HasColumnName("appearances");

                    b.Property<int?>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("birth_place");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<int?>("MinutesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_played");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shirt_number");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<int?>("StatsSeason")
                        .HasColumnType("integer")
                        .HasColumnName("stats_season");

                    b.Property<DateTimeOffset?>("StatsUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stats_updated_at");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WeightKg")
                        .HasColumnType("integer")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_athletes");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_athletes_external_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_athletes_team_id");

                    b.HasIndex("SportId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_athletes_sport_id_slug");

                    b.ToTable("athletes", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handle");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YouTubeChannelId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("you_tube_channel_id");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_handle");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_slug");

                    b.HasIndex("YouTubeChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_you_tube_channel_id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Commentator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_commentators");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_commentators_slug");

                    b.ToTable("commentators", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_competitions_external_id");

                    b.HasIndex("SportId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_sport_id_slug");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Round")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("round");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_detail");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_events_external_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_events_slug");

                    b.HasIndex("SeasonId", "StartTime")
                        .HasDatabaseName("ix_events_season_id_start_time");

                    b.HasIndex("Status", "StartTime")
                        .HasDatabaseName("ix_events_status_start_time");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Result")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("ScoreDetail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("score_detail");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_participants");

                    b.HasIndex("AthleteId")
                        .HasDatabaseName("ix_event_participants_athlete_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_event_participants_team_id");

                    b.HasIndex("EventId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_event_participants_event_id_order");

                    b.ToTable("event_participants", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_participants_team_or_athlete", "team_id IS NOT NULL OR athlete_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Opinion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<double?>("AttributionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("attribution_confidence");

                    b.Property<Guid?>("CommentatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("commentator_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsQuoteVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_quote_verified");

                    b.Property<string>("Prediction")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("prediction");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("quote");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("SpeakerLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("speaker_label");

                    b.Property<string>("SpeakerSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("speaker_source");

                    b.Property<string>("Stance")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("TimestampSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timestamp_seconds");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_opinions");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_opinions_video_id");

                    b.HasIndex("AthleteId", "Status")
                        .HasDatabaseName("ix_opinions_athlete_id_status");

                    b.HasIndex("CommentatorId", "Status")
                        .HasDatabaseName("ix_opinions_commentator_id_status");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_opinions_event_id_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_opinions_status_created_at");

                    b.HasIndex("StoryId", "Status")
                        .HasDatabaseName("ix_opinions_story_id_status");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("ix_opinions_team_id_status");

                    b.ToTable("opinions", null, t =>
                        {
                            t.HasCheckConstraint("ck_opinions_attribution_confidence", "attribution_confidence IS NULL OR (attribution_confidence >= 0 AND attribution_confidence <= 1)");
                        });
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.ProviderQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Used")
                        .HasColumnType("integer")
                        .HasColumnName("used");

                    b.HasKey("Id")
                        .HasName("pk_provider_quotas");

                    b.HasIndex("Provider", "Day")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_quotas_provider_day");

                    b.ToTable("provider_quotas", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("CompetitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_competition_id")
                        .HasFilter("is_current = true");

                    b.HasIndex("CompetitionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_competition_id_name");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FetchIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("fetch_interval_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("SportId")
                        .HasDatabaseName("ix_sources_sport_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_url");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sports");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sports_slug");

                    b.ToTable("sports", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Standing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AthleteId")
                        .HasColumnType("uuid")
                        .HasColumnName("athlete_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Drawn")
                        .HasColumnType("integer")
                        .HasColumnName("drawn");

                    b.Property<string>("Form")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("form");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_name");

                    b.Property<int>("Lost")
                        .HasColumnType("integer")
                        .HasColumnName("lost");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int?>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<string>("StatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Won")
                        .HasColumnType("integer")
                        .HasColumnName("won");

                    b.HasKey("Id")
                        .HasName("pk_standings");

                    b.HasIndex("AthleteId")
                        .HasDatabaseName("ix_standings_athlete_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_standings_team_id");

                    b.HasIndex("SeasonId", "GroupName", "Rank")
                        .HasDatabaseName("ix_standings_season_id_group_name_rank");

                    b.ToTable("standings", null, t =>
                        {
                            t.HasCheckConstraint("ck_standings_team_or_athlete", "team_id IS NOT NULL OR athlete_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AiAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("ai_attempts");

                    b.Property<string>("AiDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_data_json");

                    b.Property<DateTimeOffset?>("AiProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ai_processed_at");

                    b.Property<string>("Analysis")
                        .HasColumnType("text")
                        .HasColumnName("analysis");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("ClusterKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("cluster_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_published_at");

                    b.Property<string>("Headline")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("headline");

                    b.Property<int>("ImagePriority")
                        .HasColumnType("integer")
                        .HasColumnName("image_priority");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_live");

                    b.Property<DateTimeOffset>("LastPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_published_at");

                    b.Property<bool>("NeedsRewrite")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_rewrite");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("slug");

                    b.Property<int>("SourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_count");

                    b.Property<Guid?>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stories");

                    b.HasIndex("ClusterKey")
                        .IsUnique()
                        .HasDatabaseName("ix_stories_cluster_key");

                    b.HasIndex("LastPublishedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_stories_last_published_at");

                    b.HasIndex("NeedsRewrite")
                        .HasDatabaseName("ix_stories_needs_rewrite")
                        .HasFilter("needs_rewrite = true");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_stories_slug")
                        .HasFilter("slug IS NOT NULL");

                    b.HasIndex("SportId", "LastPublishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_stories_sport_id_last_published_at");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsNational")
                        .HasColumnType("boolean")
                        .HasColumnName("is_national");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("short_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sport_id");

                    b.Property<DateTimeOffset?>("SquadSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("squad_synced_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_teams_external_id");

                    b.HasIndex("SportId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_sport_id_slug");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("processing_error");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("processing_status");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("you_tube_video_id");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("YouTubeVideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_you_tube_video_id");

                    b.HasIndex("ChannelId", "PublishedAt")
                        .HasDatabaseName("ix_videos_channel_id_published_at");

                    b.HasIndex("ProcessingStatus", "PublishedAt")
                        .HasDatabaseName("ix_videos_processing_status_published_at");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("ChannelCommentator", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_commentators_channels_channels_id");

                    b.HasOne("RandaSports.Domain.Entities.Commentator", null)
                        .WithMany()
                        .HasForeignKey("RegularCommentatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channel_commentators_commentators_regular_commentators_id");
                });

            modelBuilder.Entity("CommentatorSport", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Commentator", null)
                        .WithMany()
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commentator_sports_commentators_commentator_id");

                    b.HasOne("RandaSports.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commentator_sports_sports_sports_id");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_teams_competitions_competitions_id");

                    b.HasOne("RandaSports.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_teams_teams_teams_id");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Article", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Source", "Source")
                        .WithMany("Articles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articles_sources_source_id");

                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_sports_sport_id");

                    b.HasOne("RandaSports.Domain.Entities.Story", "Story")
                        .WithMany("Articles")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_articles_stories_story_id");

                    b.Navigation("Source");

                    b.Navigation("Sport");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.ArticleTag", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Article", "Article")
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_tags_articles_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Athlete", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_athletes_sports_sport_id");

                    b.HasOne("RandaSports.Domain.Entities.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_athletes_teams_team_id");

                    b.Navigation("Sport");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Competition", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany("Competitions")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competitions_sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Event", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Season", "Season")
                        .WithMany("Events")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.EventParticipant", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_participants_athletes_athlete_id");

                    b.HasOne("RandaSports.Domain.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_events_event_id");

                    b.HasOne("RandaSports.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_participants_teams_team_id");

                    b.Navigation("Athlete");

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Opinion", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_opinions_athletes_athlete_id");

                    b.HasOne("RandaSports.Domain.Entities.Commentator", "Commentator")
                        .WithMany("Opinions")
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_opinions_commentators_commentator_id");

                    b.HasOne("RandaSports.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_opinions_events_event_id");

                    b.HasOne("RandaSports.Domain.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_opinions_stories_story_id");

                    b.HasOne("RandaSports.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_opinions_teams_team_id");

                    b.HasOne("RandaSports.Domain.Entities.Video", "Video")
                        .WithMany("Opinions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opinions_videos_video_id");

                    b.Navigation("Athlete");

                    b.Navigation("Commentator");

                    b.Navigation("Event");

                    b.Navigation("Story");

                    b.Navigation("Team");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Season", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Competition", "Competition")
                        .WithMany("Seasons")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Source", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sources_sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Standing", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_standings_athletes_athlete_id");

                    b.HasOne("RandaSports.Domain.Entities.Season", "Season")
                        .WithMany("Standings")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_standings_seasons_season_id");

                    b.HasOne("RandaSports.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_standings_teams_team_id");

                    b.Navigation("Athlete");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Story", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stories_sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Team", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Video", b =>
                {
                    b.HasOne("RandaSports.Domain.Entities.Channel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_videos_channels_channel_id");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Article", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Channel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Commentator", b =>
                {
                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Event", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Season", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Source", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Sport", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Story", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Team", b =>
                {
                    b.Navigation("Athletes");
                });

            modelBuilder.Entity("RandaSports.Domain.Entities.Video", b =>
                {
                    b.Navigation("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
